### PR TITLE
fix: ignore empty attributes in walrus file

### PR DESCRIPTION
**Pull request by aiwantaozi**
**Problem:**
Attributes: {} is considered as empty in walrus, walrus file treat it as meaningful value.

**Solution:**
Should unify the operation, update walrus file to treat attributes: {} as empty

**Related Issue:**
#2055

### CODE REVIEW

**Comment by thxCode** [comment]
as https://github.com/seal-io/walrus/issues/2055#issuecomment-1918467531 mentioned, can we just modify the DAO schema as below?

image

**Comment by aiwantaozi** [comment]
Updated.

**Review by thxCode — APPROVED** [review]
LGTM

**Review by alexcodelf — APPROVED** [review]
LGTM

**Pull request merged**
