### PR TITLE
refactor: update generate schema default with attributes

### PR DESCRIPTION
**Pull request by aiwantaozi**
**Problem:**
Use user input attributes while exist, compare with merge it with ops configuration, merge is more intuitive. 

**Solution:**
After discussion, it was decided that the merge operation would eventually be performed, and the mutually exclusive parts of the merge would need to be handled in the template.

**Related Issue:**
#2076

### CODE REVIEW

**Comment by thxCode** [comment]
looks like all cases are preparing for `with_attributes_`, let's shorten the testdata's filename, remove `with_attributes_`.

if we want to emphasize testing with `GenSchemaDefaultWithAttribute`, we can put all cases under `gen_schema_default_with_attribute`.

**Comment by aiwantaozi** [comment]
> looks like all cases are preparing for `with_attributes_`, let's shorten the testdata's filename, remove `with_attributes_`.
> 
> if we want to emphasize testing with `GenSchemaDefaultWithAttribute`, we can put all cases under `gen_schema_default_with_attribute`.

Each case dir includes some files shared with two cases (main.tf, schema.yaml) and other files used for specific tests. files with prefix: with_attributes are for `TestGenSchemaDefaultWithAttribute`, and without a prefix are for `TestGenSchemaDefaultPatch`.

**Review by thxCode — APPROVED** [review]
LGTM

**Review by alexcodelf — APPROVED** [review]
LGTM

**Pull request merged**
