### PR TITLE
fix: remove empty field when cli post/update resource

### PR DESCRIPTION
**Pull request by aiwantaozi**
**Problem:**
CLI calling API with value like {} may cause a validation issue. 

**Solution:**
Remove empty value before request.

**Related Issue:**
#2178

### CODE REVIEW

**Comment by gitlawr** [comment]
Should we trim resourceDefinitionMatchingRule from resource Input entity?

**Comment by aiwantaozi** [comment]
resourceDefinitionMatchingRule is in use.
https://github.com/seal-io/walrus/blob/cd09c6e3d4ab0c6dfac01572bad3368f85eca259/pkg/apis/resource/basic_view.go#L205

https://github.com/seal-io/walrus/blob/cd09c6e3d4ab0c6dfac01572bad3368f85eca259/pkg/apis/resource/basic_view.go#L319

https://github.com/seal-io/walrus/blob/cd09c6e3d4ab0c6dfac01572bad3368f85eca259/pkg/apis/resource/basic_view.go#L626

https://github.com/seal-io/walrus/blob/cd09c6e3d4ab0c6dfac01572bad3368f85eca259/pkg/apis/resource/extension_view.go#L165
...

**Review by shanewxy — APPROVED** [review]
LGTM

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
